### ISSUE TITLE
Keyboard shortcut to bring up tab menu?

### ISSUE THREAD

**Issue by Soleone** [colebemis/tabio#1]
This seems like a neat project, but I am looking to do less clicks to switch between tabs instead of more. Is there keyboard shortcut that works from any tab to bring up the menu to make this 100% keyboard usable without using the mouse at all? If not would you consider adding a shortcut? Bonus points if the shortcut is configurable.

**Comment by colebemis** [comment]
Thanks for your input! Chrome allows you to set keyboard shortcuts in the settings. More information on that [here](http://lifehacker.com/add-custom-keyboard-shortcuts-to-chrome-extensions-for-1595322121). I'll look into how I can set a shortcut by default.

**Comment by Soleone** [comment]
thanks i'll take a look to set this up myself for now. feel free to keep this issue open for you to address it in the extension directly for ease of use.

**Comment by MartinAyla** [comment]
+1 for this :)

**Comment by colebemis** [comment]
You can now open and close the extension using `Alt`+`Shift`+`T`.
