### ISSUE TITLE
Feature Request: Hotkey options

### ISSUE THREAD

**Issue by vitordino** [colebemis/tabio#11]
Option to change the letter (default `k`)
As cmd+k is used in many places* (more commonly to add links)

\*for exemple this github editor, gmail, dropbox paper, google docs.

**Comment by colebemis** [comment]
Chrome extension keyboard shortcuts can be configured in `chrome://extensions` 👍  https://www.howtogeek.com/127162/how-to-create-custom-keyboard-shortcuts-for-browser-actions-and-extensions-in-google-chrome/
