### ISSUE TITLE
Works ONLY when two Chromes are opened simultaneously

### ISSUE THREAD

**Issue by millanbrankovic** [colebemis/tabio#19]
## Expected Behavior
Should work when one Chrome is active

## Actual Behavior
Works ONLY when I have two Chromes opened

## Steps to Reproduce the Problem

  1. Open a Chrome, open a few different tabs and try to use the extension (not working)
  2. Keep Chrome opened, press cmd + n to open another Chrome instance, open few different tabs and try to use the extension, it will work ONLY if you choose a tab from another active Chrome, it will NOT work if you try to activate a tab from the same Chrome where the extension was triggered

## Specifications

  - Tabio Version: 2.0.3
  - Chrome Version: 68.0.3440.106 (Official Build) (64-bit)
  - OS Version: macOS High Sierra 10.13.6 (17G65)

**Comment by colebemis** [comment]
This was fixed in 2.0.4 https://github.com/colebemis/tabio/releases/tag/v2.0.4
👍

**Comment by millanbrankovic** [comment]
Yes, it works now like a charm :) Thanks!
