### ISSUE TITLE
Incorrect drawing sometimes when activating tabio

### ISSUE THREAD

**Issue by jondot** [colebemis/tabio#2]
Hi,
Excellent solution for tabs! thanks for your work :)
I bound `Cmd-P` to this extension via the Chrome settings, and it feels awesome and matches my Vim workflow in this regard so kudos!

One thing that happens from time to time (I think every 2nd open), is that the window doesn't draw itself right/well, see screenshot. In the screenshot, I have around 20 tabs open but it shows a strange depiction of it.

![screen shot 2015-06-04 at 9 51 10 am](https://cloud.githubusercontent.com/assets/83390/7978576/874cc6f2-0a9f-11e5-896e-8e42eab594dd.png)

Once I type something, the search re-renders the window and everything is OK

**Comment by colebemis** [comment]
Thanks for letting me know. I've noticed this a few times myself. I'm not sure if there is a bug in my code or if it's a problem with Chrome. I'll continue to look into it.

**Comment by colebemis** [comment]
It seems that this is an issue with Chrome itself. Had to use a hack to get around this problem: https://github.com/colebemis/tabio/blob/402e595dddeaf1531e8812016a49cbfcd55ce0e4/src/components/App.jsx#L33-L56
