### ISSUE TITLE
Toggle/close the extension via keyboard shortcut. 

### ISSUE THREAD

**Issue by politicus** [colebemis/tabio#3]
I just tested your extension and the "Tab ahead" extension. 

I find your way better. The only thing "Tab ahead" does better is that I can close the extension via the esc key and do not have to click anywhere (-> no need to use the trackpad or the mouse). 

So, my feature request is the following being able to close the search bar of the extension via the esc key or use the same keyboard shortcut used to launch the extension to close it.

**Comment by colebemis** [comment]
You can now open and close the extension using `Alt`+`Shift`+`T`. This can be customized in the Chrome extension settings page. More information on that [here](http://lifehacker.com/add-custom-keyboard-shortcuts-to-chrome-extensions-for-1595322121).

**Comment by politicus** [comment]
Awesome! Thank you!
