### ISSUE TITLE
performance: after pressing keyboard shordcut and typing initial presses don't get recognized

### ISSUE THREAD

**Issue by Soleone** [colebemis/tabio#4]
I set up a keyboard shortcut via [this](http://lifehacker.com/add-custom-keyboard-shortcuts-to-chrome-extensions-for-1595322121) and that's working fine. the problem is:
1. I press the shortcut
2. and then start typing immediately for the name of the tab i want to open 
3. there's a noticeable delay until the list of open tabs shows after (1)
4. my initial keystrokes have been ignored and only the keystrokes typed after the list window has been opened get recognized
5. i have to start typing from the beginning again

for what it's worth i have 10 tabs open on OSX Yosemite 10.10.3 with Chrome Version 43.0.2357.124 (64-bit).

i hope i explained the problem well. I can't really use the extension with this issue I'm afraid.

Optimally I'd expect that the list window opens faster with no delay (maybe somehow tabs can get cached whenever a new tab is opened/closed as opposed to dynamically reading them when the extension is activated) and if that doesn't work at least that no keystrokes "get swallowed" after i press the keyboard shortcut to open the extension.

**Comment by colebemis** [comment]
Hi @Soleone,

I've also notices a slight delay between the time the keyboard shortcut is pressed and when Chrome opens the extension popup. I wish the Chrome opened the popup a little faster. That being said, I just released version 2 of Tabio which comes with some performance improvements. Check it out and let me know what you think 👍
